"""Add ApprovedEmail table

Revision ID: 71faf80cbba1
Revises: 2239fe32df9f
Create Date: 2025-09-11 12:01:36.680281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71faf80cbba1'
down_revision = '2239fe32df9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_temp_password', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_temp_password')

    # ### end Alembic commands ###
