"""Add ApprovedEmail table

Revision ID: a8811f503746
Revises: 71faf80cbba1
Create Date: 2025-10-09 10:15:43.638625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8811f503746'
down_revision = '71faf80cbba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_column('user_type')
        batch_op.drop_column('visit_count')

    # ### end Alembic commands ###
